# values.yaml
chromadb:
  image:
    repository: chromadb/chromadb
    tag: latest
  service:
    type: ClusterIP
    port: 8000
  resources:
    requests:
      cpu: 500m
      memory: 512Mi
    limits:
      cpu: "1"
      memory: 1Gi

langchain:
  image:
    repository: myrepo/langchain-rag
    tag: latest
  service:
    type: ClusterIP
    port: 8080
  resources:
    requests:
      cpu: 500m
      memory: 512Mi
    limits:
      cpu: "1"
      memory: 1Gi

ollama:
  image:
    repository: localhost:5000/ollama
    tag: latest
  service:
    type: ClusterIP
    port: 11434
  resources:
    requests:
      cpu: 500m
      memory: 512Mi
    limits:
      cpu: "2"
      memory: 2Gi

# ingress configuration (commented out for now)
ingress:
  enabled: false # set to true to enable Ingress
  className: "" # optional ingress class
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: [] # e.g. [{ hosts: ["chart-example.local"], secretName: "tls-secret" }]

# horizontal pod autoscaling (commented out for now)
autoscaling:
  enabled: false # set to true to enable HPA
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80

nameOverride: ""
fullnameOverride: ""
